#ifndef INA226_WE_LEGACY_H_
#define INA226_WE_LEGACY_H_

#define AVERAGE_1 _Pragma("GCC error \"AVERAGE_1 is deprecated – please use INA226_AVERAGE_1\"")
#define AVERAGE_4 _Pragma("GCC error \"AVERAGE_4 is deprecated – please use INA226_AVERAGE_4\"")
#define AVERAGE_16 _Pragma("GCC error \"AVERAGE_16 is deprecated – please use INA226_AVERAGE_16\"")
#define AVERAGE_64 _Pragma("GCC error \"AVERAGE_64 is deprecated – please use INA226_AVERAGE_64\"")
#define AVERAGE_128 _Pragma("GCC error \"AVERAGE_128 is deprecated – please use INA226_AVERAGE_128\"")
#define AVERAGE_256 _Pragma("GCC error \"AVERAGE_256 is deprecated – please use INA226_AVERAGE_256\"")
#define AVERAGE_512 _Pragma("GCC error \"AVERAGE_512 is deprecated – please use INA226_AVERAGE_512\"")
#define AVERAGE_1024 _Pragma("GCC error \"AVERAGE_1024 is deprecated – please use INA226_AVERAGE_1024\"")
#define CONV_TIME_140 _Pragma("GCC error \"CONV_TIME_140 is deprecated – please use INA226_CONV_TIME_140\"")
#define CONV_TIME_204 _Pragma("GCC error \"CONV_TIME_204 is deprecated – please use INA226_CONV_TIME_204\"")
#define CONV_TIME_332 _Pragma("GCC error \"CONV_TIME_332 is deprecated – please use INA226_CONV_TIME_332\"")
#define CONV_TIME_588 _Pragma("GCC error \"CONV_TIME_588 is deprecated – please use INA226_CONV_TIME_588\"")
#define CONV_TIME_1100 _Pragma("GCC error \"CONV_TIME_1100 is deprecated – please use INA226_CONV_TIME_1100\"")
#define CONV_TIME_2116 _Pragma("GCC error \"CONV_TIME_2116 is deprecated – please use INA226_CONV_TIME_2116\"")
#define CONV_TIME_4156 _Pragma("GCC error \"CONV_TIME_4156 is deprecated – please use INA226_CONV_TIME_4156\"")
#define CONV_TIME_8244 _Pragma("GCC error \"CONV_TIME_8244 is deprecated – please use INA226_CONV_TIME_8244\"")
#define POWER_DOWN _Pragma("GCC error \"POWER_DOWN is deprecated – please use INA226_POWER_DOWN\"")
#define TRIGGERED _Pragma("GCC error \"TRIGGERED is deprecated – please use INA226_TRIGGERED\"")
#define CONTINUOUS _Pragma("GCC error \"CONTINUOUS is deprecated – please use INA226_CONTINUOUS\"")
#define SHUNT_OVER _Pragma("GCC error \"SHUNT_OVER is deprecated – please use INA226_SHUNT_OVER\"")
#define SHUNT_UNDER _Pragma("GCC error \"SHUNT_UNDER is deprecated – please use INA226_SHUNT_UNDER\"")
#define BUS_OVER _Pragma("GCC error \"BUS_OVER is deprecated – please use INA226_BUS_OVER\"")
#define BUS_UNDER _Pragma("GCC error \"BUS_UNDER is deprecated – please use INA226_BUS_UNDER\"")
#define POWER_OVER _Pragma("GCC error \"POWER_OVER is deprecated – please use INA226_POWER_OVER\"")
#define CURRENT_OVER _Pragma("GCC error \"CURRENT_OVER is deprecated – please use INA226_CURRENT_OVER\"")
#define CURRENT_UNDER _Pragma("GCC error \"CURRENT_UNDER is deprecated – please use INA226_CURRENT_UNDER\"")
#define CONV_READY _Pragma("GCC error \"CONV_READY is deprecated – please use INA226_CONV_READY\"")
#define MA_400 _Pragma("GCC error \"MA_400 is deprecated – current ranges are not supported anymore\"")
#define MA_800 _Pragma("GCC error \"MA_800 is deprecated – current ranges are not supported anymore\"")

#endif